title: Paidge
author: Eugene Lee
email: eugene@paidge.com
description: Research notes on Personalized Artificial Intelligence on the Edge.
theme: minima
markdown: kramdown
baseurl: ""
url: "https://paidge.com"
github_username: eugenelet
twitter_username: eugenelet
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
google_site_verification: Jn8JLXej9qcTHIuNcc6DU2KMylAuvUk7vAWIyLVnadU
icon: "favicon.png"
