import json
import os
import re
import argparse
from openai import OpenAI
from pypdf import PdfReader

# Initialize Ollama client
client = OpenAI(base_url="http://localhost:11434/v1", api_key="ollama")

PDF_DIR = "./papers"
DB_FILE = "./_data/paper_db.json"
BASE_KNOWLEDGE_DIR = "./notes"
MASTER_PAGE_FILE = "./reading-list.md"

TAXONOMY = {
    "Test-Time Adaptation": "🔄",
    "In-Context Learning": "🧠",
    "Efficient Architectures": "⚡",
    "Multimodal & Vision": "👁️",
    "Embodied AI & Robotics": "🤖",
    "Theory & Optimization": "📐",
}


def derive_arxiv_date(arxiv_id):
    """Deterministically converts an arXiv ID (e.g. '2605.12345') into an ISO '2026-05' date"""
    if not arxiv_id:
        return None
    match = re.match(r"^(\d{2})(\d{2})\.", arxiv_id)
    if match:
        year, month = match.groups()
        return f"20{year}-{month}"
    return None


def load_db():
    if not os.path.exists(DB_FILE):
        return {}

    with open(DB_FILE, "r", encoding="utf-8") as f:
        db = json.load(f)

    patched = False
    for filename, data in db.items():
        if "pub_date" not in data:
            aid = extract_arxiv_id(filename, "")
            data["pub_date"] = derive_arxiv_date(aid) or "2026-01"
            patched = True
        
        if "full_title" not in data:
            data["full_title"] = data.get("short_title", "Unknown Title")
            patched = True

    if patched:
        save_db(db)

    return db


def save_db(db):
    os.makedirs(os.path.dirname(DB_FILE), exist_ok=True)
    with open(DB_FILE, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)


def extract_arxiv_id(filename, text):
    match = re.search(r"\b\d{4}\.\d{4,5}(?:v\d+)?\b", filename)
    if match:
        return match.group(0)
    match = re.search(r"\b\d{4}\.\d{4,5}(?:v\d+)?\b", text)
    return match.group(0) if match else None


def clean_slug(name):
    return re.sub(r'[\\/*?:"<>|]', "", name).strip().replace(" ", "_").lower()


def extract_key_sections(pdf_path):
    try:
        reader = PdfReader(pdf_path)
        num_pages = len(reader.pages)
        pages_to_read = set([0, 1, 2])

        ref_page = next(
            (
                i
                for i in range(num_pages)
                if any(
                    k in (reader.pages[i].extract_text() or "").lower()
                    for k in ["references", "bibliography"]
                )
            ),
            None,
        )

        if ref_page and ref_page > 2:
            pages_to_read.update([ref_page - 2, ref_page - 1])
        else:
            pages_to_read.update([max(0, num_pages - 2), max(0, num_pages - 1)])

        raw_text = "\n".join(
            f"--- PAGE {i+1} ---\n{reader.pages[i].extract_text() or ''}"
            for i in sorted(pages_to_read)
            if i < num_pages
        )
        
        # 🛡️ THE FIX: Scrub invalid unicode characters (lone surrogates) generated by complex math fonts
        return raw_text.encode('utf-8', 'ignore').decode('utf-8')
        
    except Exception as e:
        print(f"PDF Error in {pdf_path}: {e}")
        return None


def synthesize_frontier(topic, paper_list):
    if not paper_list:
        return "Awaiting empirical literature for this vector."

    takeaways_bulleted = "\n".join(f"- [{p['short_title']}]: {p['takeaway']}" for p in paper_list)

    prompt = f"""
    You are an elite academic AI research director. Look at the core empirical takeaways extracted from the literature tracked under the research pillar '{topic}':
    
    {takeaways_bulleted}
    
    Synthesize these distinct points into a dense, cohesive 2-sentence summary of the "Current Field Frontier". 
    Focus strictly on: What is the overarching paradigm shift, the shared mathematical trajectory, or the collective bottleneck these papers point toward? 
    
    CRITICAL: You MUST cite the specific papers that contribute to your claims using their exact bracketed short titles.
    Example: "This bottleneck is bypassed by localized projections [CoPA] and predictive loss [NDP]."
    RULE: Do NOT combine brackets. Always write them separately (e.g., [PaperA] [PaperB]).
    Write strictly about the science. Do not use conversational filler.
    """

    res = client.chat.completions.create(
        model="qwen3.6:35b-mlx",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
    )
    
    frontier_text = res.choices[0].message.content.strip()
    
    for p in paper_list:
        citation_target = f"[{p['short_title']}]"
        badge_html = f'<a href="{p["web_url"]}" class="citation-badge">{p["short_title"]}</a>'
        frontier_text = frontier_text.replace(citation_target, badge_html)
        
    return frontier_text


def analyze_paper(text):
    allowed_list_str = ", ".join(f'"{k}"' for k in TAXONOMY.keys())
    prompt = f"""
    Analyze this machine learning paper. 
    You MUST categorize it strictly into ONE of these exact 6 Primary Topics: [{allowed_list_str}].
    
    Output strictly in this format:
    
    ---METADATA---
    Primary Category: [Pick exactly one from the 6 allowed topics]
    Short Title: [Clean 3-5 word title for web slug]
    Full Title: [The exact, unabridged title of the paper]
    Pub Date: [YYYY-MM format, e.g. 2026-05]
    Core Takeaway: [A single punchy, high-signal sentence summarizing the advancement]
    ---END METADATA---
    
    # [Full Paper Title]
    
    #### 🚀 Technical Novelty
    * **Mechanism**: [Concrete advancement]
    * **Nuance**: [How it differs from prior SOTA]
    
    #### 💡 Yield
    - [Key theoretical or empirical results]
    
    #### ⚠️ Limitations
    - [Authors' admitted constraints]

    Text to analyze:
    {text}
    """

    res = client.chat.completions.create(
        model="qwen3.6:35b-mlx",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )
    return res.choices[0].message.content


def render_master_reading_list(db, updated_topics, force_synthesis=False):
    if "_frontiers" not in db:
        db["_frontiers"] = {}

    grouped = {t: [] for t in TAXONOMY.keys()}
    for key, entry in db.items():
        if key == "_frontiers":
            continue
        cat = entry.get("topic")
        if cat in grouped:
            grouped[cat].append(entry)

    md = """---
layout: page
title: Reading List
permalink: /reading-list/
---

# 📚 Centralized Reading List & Field Advancements

Select a research vector below to isolate the literature and view its trend.

<div class="topic-filter-container" style="display: flex; gap: 8px; flex-wrap: wrap; margin: 1.5rem 0 2rem 0;">
<button class="topic-pill active" onclick="filterTopic('all', this)">🌟 All Advancements</button>
"""

    for topic, emoji in TAXONOMY.items():
        if grouped[topic]:
            slug = clean_slug(topic)
            md += f'<button class="topic-pill" onclick="filterTopic(\'{slug}\', this)">{emoji} {topic}</button>\n'

    md += "</div>\n\n"

    # FIXED: Converted CSS to Light Theme variables for legibility
    md += """<style>
  .topic-pill { padding: 6px 14px; background: #f8fafc; border: 1px solid #cbd5e1; color: #475569; border-radius: 20px; cursor: pointer; font-size: 0.85rem; font-weight: 600; transition: all 0.2s; }
  .topic-pill.active { background: #3253DC; color: white; border-color: #6382f2; box-shadow: 0 0 8px rgba(50, 83, 220, 0.4); }
  .topic-pill:hover:not(.active) { background: #e2e8f0; color: #0f172a; }
  
  .timeline-container { border-left: 2px solid #3253DC; margin-left: 12px; padding-left: 24px; position: relative; margin-top: 2rem; margin-bottom: 3rem; }
  .timeline-item { position: relative; margin-bottom: 2.5rem; }
  .timeline-node { position: absolute; left: -30px; top: 6px; width: 10px; height: 10px; background: #3253DC; border-radius: 50%; box-shadow: 0 0 8px rgba(99, 130, 242, 0.4); border: 2px solid #ffffff; z-index: 10;}
  .timeline-date { background: #f1f5f9; color: #475569; border: 1px solid #cbd5e1; padding: 2px 8px; border-radius: 4px; font-family: monospace; font-size: 0.8rem; letter-spacing: 0.5px; }
  .paper-link { color: #0f172a; font-weight: 700; font-size: 1.05rem; text-decoration: none; transition: color 0.2s; }
  .paper-link:hover { color: #3253DC; }
  .full-title-sub { font-size: 0.8rem; color: #64748b; font-style: italic; margin-top: 4px; margin-bottom: 4px; padding-left: 2px; }
  .takeaway-text { color: #334155; font-size: 0.95rem; line-height: 1.5; margin-top: 8px; }
  
  /* Citation Badge for Light Theme */
  .citation-badge { display: inline-block; font-size: 0.7rem; font-family: monospace; background: #eff6ff; color: #3253DC; border: 1px solid #bfdbfe; padding: 2px 6px; border-radius: 4px; text-decoration: none; vertical-align: middle; margin: 0 4px; box-shadow: 0 1px 2px rgba(0,0,0,0.05); transition: all 0.2s; position: relative; top: -1px;}
  .citation-badge:hover { background: #3253DC; color: #ffffff; box-shadow: 0 0 6px rgba(50, 83, 220, 0.4); }
</style>

<script>
  function filterTopic(slug, btnEl) {
    document.querySelectorAll('.topic-pill').forEach(b => b.classList.remove('active'));
    btnEl.classList.add('active');
    document.querySelectorAll('.topic-section-group').forEach(group => {
      group.style.display = (slug === 'all' || group.getAttribute('data-topic') === slug) ? 'block' : 'none';
    });
  }
</script>

"""

    for topic, papers in grouped.items():
        if not papers:
            continue

        papers.sort(key=lambda x: x.get("pub_date", "0000-00"), reverse=True)

        slug = clean_slug(topic)
        emoji = TAXONOMY[topic]

        if force_synthesis or topic in updated_topics or topic not in db["_frontiers"]:
            print(f"   🧠 Synthesizing macro-frontier for '{topic}'...")
            db["_frontiers"][topic] = synthesize_frontier(topic, papers)
            save_db(db)

        frontier_text = db["_frontiers"][topic]

        # FIXED: Removed ALL indentation from injected HTML strings
        md += f'<div class="topic-section-group" data-topic="{slug}" markdown="1">\n\n'
        md += f"## {emoji} {topic}\n\n"

        md += f"""<div style="background: #16181d; border: 1px solid #2d3748; border-left: 4px solid #3253DC; padding: 1.25rem; border-radius: 4px 8px 8px 4px; margin: 1.25rem 0 2rem 0; color: #e2e8f0; font-size: 0.95rem; line-height: 1.6;" markdown="1">
<div style="display: flex; align-items: center; gap: 8px; margin-bottom: 6px;">
<span style="font-size: 1.1rem;">🧭</span>
<strong style="color: #6382f2; font-size: 0.85rem; font-family: monospace; text-transform: uppercase; letter-spacing: 1px;">Research Trend</strong>
</div>

{frontier_text}

</div>\n\n"""

        md += '<div class="timeline-container">\n'
        for p in papers:
            date_badge = p.get("pub_date", "2026-01")
            short_t = p['short_title']
            full_t = p.get('full_title', short_t)
            
            full_title_html = ""
            if short_t.lower() != full_t.lower():
                full_title_html = f'\n<div class="full-title-sub">{full_t}</div>'
            
            # FIXED: Flushed left to avoid the `<pre><code>` trap
            md += f"""<div class="timeline-item">
<div class="timeline-node"></div>
<div style="display: flex; align-items: baseline; gap: 10px; flex-wrap: wrap;">
<span class="timeline-date">{date_badge}</span>
<a href="{p['web_url']}" class="paper-link">{short_t}</a>
</div>{full_title_html}
<div class="takeaway-text" markdown="1">

<span style="color: #64748b; font-family: monospace; font-weight: bold;">└─</span> {p['takeaway']}

</div>
</div>\n"""
            
        md += "</div>\n\n</div>\n\n"

    with open(MASTER_PAGE_FILE, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"🔄 Rebuilt master index: {MASTER_PAGE_FILE}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--force-synthesis", action="store_true", help="Force the LLM to rewrite all topic frontiers")
    args = parser.parse_args()

    db = load_db()
    os.makedirs(BASE_KNOWLEDGE_DIR, exist_ok=True)
    newly_ingested_topics = set()

    for file in os.listdir(PDF_DIR):
        if not file.endswith(".pdf") or file in db:
            continue

        print(f"\n📑 Ingesting: {file}...")
        pdf_path = os.path.join(PDF_DIR, file)
        text = extract_key_sections(pdf_path)

        if not text:
            continue

        arxiv_id = extract_arxiv_id(file, text)
        arxiv_url = f"https://arxiv.org/abs/{arxiv_id}" if arxiv_id else None

        raw_meta = analyze_paper(text)

        try:
            meta_box = re.search(
                r"---METADATA---(.*)---END METADATA---", raw_meta, re.DOTALL
            ).group(1)
            topic = re.search(r"Primary Category:\s*(.*)", meta_box).group(1).strip()
            short_title = re.search(r"Short Title:\s*(.*)", meta_box).group(1).strip()
            
            full_title_match = re.search(r"Full Title:\s*(.*)", meta_box)
            full_title = full_title_match.group(1).strip() if full_title_match else short_title
            
            takeaway = re.search(r"Core Takeaway:\s*(.*)", meta_box).group(1).strip()
            content_md = re.sub(
                r"---METADATA---.*---END METADATA---", "", raw_meta, flags=re.DOTALL
            ).strip()

            pub_date = derive_arxiv_date(arxiv_id)
            if not pub_date:
                date_match = re.search(r"Pub Date:\s*(.*)", meta_box)
                pub_date = date_match.group(1).strip() if date_match else "2026-01"

            matched_topic = next((k for k in TAXONOMY.keys() if k in topic), None)
            if not matched_topic:
                matched_topic = "Theory & Optimization"

            folder_slug = clean_slug(matched_topic)
            file_slug = clean_slug(short_title)
            target_dir = os.path.join(BASE_KNOWLEDGE_DIR, folder_slug)
            os.makedirs(target_dir, exist_ok=True)

            disk_path = os.path.join(target_dir, f"{file_slug}.md")
            web_path = f"/notes/{folder_slug}/{file_slug}.html"

            note_header = f"""---
layout: page
title: "{short_title}"
parent: "{matched_topic}"
---

"""
            src_str = f"**🔗 Source:** [arXiv]({arxiv_url})\n\n" if arxiv_url else ""
            full_note = note_header + src_str + content_md

            with open(disk_path, "w", encoding="utf-8") as f:
                f.write(full_note)

            db[file] = {
                "file": file,
                "short_title": short_title,
                "full_title": full_title,
                "topic": matched_topic,
                "takeaway": takeaway,
                "pub_date": pub_date,
                "web_url": web_path,
                "arxiv_url": arxiv_url,
            }
            save_db(db)
            newly_ingested_topics.add(matched_topic)
            print(f"   ✓ Succeeded: {short_title} ({pub_date})")

        except Exception as e:
            print(f"   ✗ AI Parsing Failed for {file}: {e}")

    render_master_reading_list(db, newly_ingested_topics, force_synthesis=args.force_synthesis)


if __name__ == "__main__":
    main()